Dependency update workflow: Only show pytest failures

diff --git a/.github/workflows/dependency_update_check.yaml b/.github/workflows/dependency_update_check.yaml
--- a/.github/workflows/dependency_update_check.yaml
+++ b/.github/workflows/dependency_update_check.yaml
@@ -150,7 +150,8 @@ jobs:
 
           echo -e "\n### Pytest Results" >> ../reports.md
           echo "\`\`\`" >> ../reports.md
-          docker exec django_backend uv run pytest --cov=. --cov-report=term-missing --cov-fail-under=85 --cov-config=pyproject.toml -vv 2>&1 | tee -a reports.md || true
+          # Note: We run pytest with --tb=line to only record the failures.
+          docker exec django_backend uv run pytest --tb=line --cov=. --cov-report=term-missing --cov-fail-under=85 --cov-config=pyproject.toml -vv 2>&1 | tee -a reports.md || true
           echo "\`\`\`" >> ../reports.md
 
       - name: Run Frontend Tests
