Dependency update workflow: Fixes for quiet pytest output

diff --git a/.github/workflows/dependency_update_check.yaml b/.github/workflows/dependency_update_check.yaml
--- a/.github/workflows/dependency_update_check.yaml
+++ b/.github/workflows/dependency_update_check.yaml
@@ -148,10 +148,10 @@ jobs:
           cd ..
           docker compose --env-file .env.dev up backend --build -d
 
-          # Note: We run pytest with -q --disable-warnings --tb=line to only record the failures in a quiet output.
+          # Note: We run pytest with --quiet --disable-warnings --tb=line to only record the failures in a quiet output.
           echo -e "\n### Pytest Results" >> ../reports.md
           echo "\`\`\`" >> ../reports.md
-          docker exec django_backend uv run pytest -q --disable-warnings --tb=line --cov=. --cov-report=term-missing --cov-fail-under=85 --cov-config=pyproject.toml -vv 2>&1 | tee -a reports.md || true
+          docker exec django_backend uv run pytest --quiet --disable-warnings --tb=line --cov=. --cov-report=term-missing --cov-fail-under=85 --cov-config=pyproject.toml 2>&1 | tee -a reports.md || true
           echo "\`\`\`" >> ../reports.md
 
       - name: Run Frontend Tests
